# Standards: 1.2
---
- name: Install required packages
  loop: "{{ apache_general_packages + apache_extra_packages }}"
  package:
    name: "{{ item }}"
    state: present
  tags:
    - apache

- name: Write security config
  notify:
    - Restart apache
  template:
    src: security.j2
    dest: /etc/apache2/conf-available/security.conf
  tags:
    - apache

- name: Write errors config
  notify:
    - Restart apache
  template:
    src: errors.j2
    dest: /etc/apache2/conf-available/localized-error-pages.conf
  tags:
    - apache

- name: Write ports config
  notify:
    - Restart apache
  template:
    src: ports.j2
    dest: /etc/apache2/ports.conf
  tags:
    - apache

- name: Write default config
  notify:
    - Restart apache
  template:
    src: default.j2
    dest: /etc/apache2/sites-available/000-default.conf
  tags:
    - apache

- name: Enable defined modules
  loop: "{{ apache_general_modules + apache_extra_modules }}"
  notify:
    - Restart apache
  apache2_module:
    name: "{{ item.name | default(item) }}"
    force: "{{ item.force | default(False) }}"
    ignore_configcheck: "{{ item.ignore_configcheck | default(False) }}"
    identifier: "{{ item.identifier | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  tags:
    - apache

- name: Remove index page
  when: not apache_keep_index
  file:
    path: /var/www/html/index.html
    state: absent
  tags:
    - apache

- name: Override index page
  when: apache_keep_index
  copy:
    content: "{{ apache_index_content | default('') }}"
    dest: /var/www/html/index.html
    force: True
  tags:
    - apache

- name: Copy error pages
  notify:
    - Reload apache
  copy:
    src: "{{ apache_error_pages }}"
    dest: /usr/share/apache2
  tags:
    - apache

- name: Start apache service
  systemd:
    name: apache2
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - apache

- name: Include exporter tasks
  when: apache_exporter_enabled | default(False)
  include: exporter.yml
  tags:
    - apache
    - apache-exporter

...
