---
- name: Reload apache
  ansible.builtin.systemd:
    name: apache2
    state: reloaded
    daemon_reload: True

- name: Restart apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted
    daemon_reload: True

- name: Restart apache-exporter
  ansible.builtin.systemd:
    name: apache-exporter
    state: restarted
    daemon_reload: yes

...
